/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/V4Jw13CXVQw
 */
import Link from "next/link"

export function homepage() {
  return (
    <>
      <section className="bg-green-50 dark:bg-green-900 py-12 md:py-24 lg:py-32">
        <div className="container mx-auto px-4 md:px-6 text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-green-900 dark:text-green-100">
            Sustainable Development Goals
          </h1>
          <p className="mt-4 text-xl md:text-2xl text-green-800 dark:text-green-200">
            Our commitment to a sustainable future
          </p>
          <Link
            className="inline-flex mt-8 items-center justify-center rounded-md bg-green-700 px-8 py-3 text-sm font-medium text-white hover:bg-green-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-green-500"
            href="#"
          >
            Explore Goals
          </Link>
        </div>
      </section>
      <nav className="sticky top-0 z-10 bg-white dark:bg-gray-800 shadow-md py-2">
        <div className="container mx-auto px-4 md:px-6 flex justify-center space-x-4">
          <Link className="text-green-900 dark:text-green-100 hover:text-green-700 dark:hover:text-green-300" href="#">
            Goal 1
          </Link>
          <Link className="text-green-900 dark:text-green-100 hover:text-green-700 dark:hover:text-green-300" href="#">
            Goal 2
          </Link>
        </div>
      </nav>
      <section
        className="container mx-auto px-4 md:px-6 py-12 md:py-24 lg:py-32 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
        id="goals"
      >
        <Link className="border-2 border-green-200 dark:border-green-800 p-4 rounded-lg" href="#">
          <article className="flex items-center space-x-4" id="goal1">
            <svg
              className=" w-16 h-16 text-green-700 dark:text-green-300"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 13V2l8 4-8 4" />
              <path d="M20.55 10.23A9 9 0 1 1 8 4.94" />
              <path d="M8 10a5 5 0 1 0 8.9 2.02" />
            </svg>
            <div>
              <h2 className="text-2xl font-bold text-green-900 dark:text-green-100">Goal 1</h2>
              <p className="mt-2 text-green-800 dark:text-green-200">Description for Goal 1</p>
            </div>
          </article>
        </Link>
        <Link className="border-2 border-green-200 dark:border-green-800 p-4 rounded-lg" href="#">
          <article className="flex items-center space-x-4" id="goal2">
            <svg
              className=" w-16 h-16 text-green-700 dark:text-green-300"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 13V2l8 4-8 4" />
              <path d="M20.55 10.23A9 9 0 1 1 8 4.94" />
              <path d="M8 10a5 5 0 1 0 8.9 2.02" />
            </svg>
            <div>
              <h2 className="text-2xl font-bold text-green-900 dark:text-green-100">Goal 2</h2>
              <p className="mt-2 text-green-800 dark:text-green-200">Description for Goal 2</p>
            </div>
          </article>
        </Link>
      </section>
    </>
  )
}
